define({
  root: {
    heading: 'Share',
    subHeading: 'Share this map',
    urlTitle: "Esri ArcGIS - {title}",
    urlSummary: "Check out this map - {summary}",
    widgetLabel: "Share",
    clipboard: "Copy to clipboard",
    sendLink: "Send a link",
    embedMap: "Embed map",
    copied: "Copied"
  },
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "hu": 1,
  "id": 1,
  "it": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nl": 1,
  "nb": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "sl": 1,
  "ru": 1,
  "su": 1,
  "sr": 1,
  "sv": 1,
  "tr": 1,
  "th": 1,
  "uk": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});